server:
  port: 41000

websocket:
  enable: true
  port: 41001

tcpsocket:
  enable: false # 暂时不开启
  port: 41002

spring:
  data:
    redis:
      host: 192.168.1.7
      port: 6379
      database: 1
      password: 123456
      # 读超时
      timeout: 3000
      # 连接超时
      connectTimeout: 6000
      # Lettuce连接池
      lettuce:
        pool:
          # 最小空闲连接
          min-idle: 5
          # 最大空闲连接
          max-idle: 10
          # 最大连接数
          max-active: 100
          # 连接分配应该阻塞的最大时间
          max-wait: 2000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.7:3306/im?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB




mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.demo.io.web.model
  global-config:
    # 数据库相关配置
    db-config:
      # ID自增
      id-type: AUTO
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
    banner: false
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出到控制台
  #    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 结合logback输出到日志文件。日志等级为trace才能输出。要么自己实现一个类再用日志记录
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

redis:
  mq:
    streams:
      # key名称
      - name:  IM:UNREAD:PUSH:PRIVATE
        groups:
          # 消费组名称
          - name: PRIVATE-MESSAGE-GROUP
            # 消费者名称
            consumers: PRIVATE-MESSAGE-GROUP-A
      # key2
#      - name: RARSP:REPORT:READ:BLC
#        groups:
#          - name: BLC_GROUP
#            consumers: BLC-CONSUMER-A,BLC-CONSUMER-B
      # key3
#      - name: RARSP:REPORT:READ:HD
#        groups:
#          - name: HD_GROUP
#            consumers: HD-CONSUMER-A,HD-CONSUMER-B

minio:
  endpoint: http://192.168.1.7:9000
  account: wuhou
  password: wuhoumusic321